### ISSUE TITLE
Topics Changed

### ISSUE THREAD

**Issue by tmayse** [raleighlittles/OReilly_Book_ID_Parser#1]
Safari Books Online/O'Reilly Learning has re-categorized their library into the following topics:

- Business
- Career Development
- Data
- Design
- Hardware
- Math, Science, Engineering
- Other
- Security
- Software Development
- System Administration
- Travel & Hobbies
- Web & Mobile

Causing an error when running the script.

**Comment by raleighlittles** [comment]
Thanks for submitting a pull request about it, @tmayse . I'll merge it and mark this issue as resolved!

**Comment by raleighlittles** [comment]
Closed in #2
